defaults:

  - common_environment
  - _self_

# Environment Name
env_name:           ['custom','SafeEnv']

# Safety Parameters
safety_threshold:   0.6

# Test and Violation Environments
test_environment:       true
violation_environment:  true
test_env_epochs:        1
violation_env_epochs:   100
test_episode_number:    10
