min_epochs:         2_000
max_epochs:         4_000
precision:          16-mixed

early_stopping:     True
patience:           750

record_video:       True
record_epochs:      150

profiler:           simple
use_profiler:       False
compilation_mode:   default
torch_compilation:  True
fast_dev_run:       False
