seed:               123

samples_per_epoch:  10_000
min_epochs:         2_000
max_epochs:         4_000
precision:          16

early_stopping:     True
patience:           750

tau:                0.005
epsilon:            0.1
smooth_lambda:      0.01

record_video:       True
record_epochs:      150

use_profiler:       False
fast_dev_run:       False
