defaults:

  - agent: wcsac+
  - entropy_params: default_entropy
  - cost_params: default_cost
  - _self_

training_params:

  env:                Safexp-PointGoal1-v0
  seed:               123
  samples_per_epoch:  10_000
  epochs:             10_000
  patience:           1_000
  tau:                0.005
  epsilon:            0.1
  smooth_lambda:      0.01

utilities_params:

  early_stopping:     True
  record_video:       True
  record_epochs:      100
  fast_dev_run:       False
