defaults:

  - agent: wcsac+
  - entropy_params: default_entropy
  - cost_params: default_cost
  - environment_params: simple_environment
  - _self_

training_params:

  seed:               123
  samples_per_epoch:  10_000
  epochs:             10_000
  patience:           500
  tau:                0.005
  epsilon:            0.1
  smooth_lambda:      0.01

utilities_params:

  early_stopping:     True
  use_profiler:       False
  record_video:       True
  record_epochs:      100
  fast_dev_run:       False

hydra:  
  run:
    dir: /home/davide/ROS/meta_constrained_RL_ws/src/Constrained_RL/safe_wcsac+/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
